version: "3"
services:
  mysql_db:
    image: mariadb:10.5
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_db_path:/var/lib/mysql
    ports:
      - 13306:3306
  app:
    build: .
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      BUNDLE_PATH: /bundle
    volumes:
      - ./:/app/:cached
      - bundle_path:/bundle
    ports:
      - 9393:9393
    depends_on:
      - mysql_db
    stdin_open: true
    tty: true
volumes:
  bundle_path:
  mysql_db_path:
